In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [4]:
ghg_emissions = pd.read_excel(Path("ghg epds.xlsx"), skiprows=5)

In [5]:
ghg_emissions.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,EPD reference,GWP emissions,Functional unit,Conversion factor to 1kg,GWP 1kg (kg),Use type,Material,GWP avg,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,NaN,NaN,Concrete,CRH Concrete A/S,66.69,1 m^2,0.00267,0.178062,Wall element,Concrete,0.206481,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,CRH Concrete A/S,174.00,1 m^3,0.00135,0.234900,Leca-block,Brick,0.189735,NaN,NaN,NaN,NaN
2,NaN,NaN,Avg,NaN,NaN,NaN,NaN,0.206481,NaN,Wood,0.055150,NaN,NaN,NaN,NaN
3,NaN,NaN,Brick,Egernsund Wienerberger A/S,209.24,1 tonne,0.00100,0.209240,"walls, pillars and partitions",Steel,1.105450,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,Petersminde Teglværk,170.23,1 tonne,0.00100,0.170230,"walls, pillars and partitions",Glass,2.650200,NaN,NaN,NaN,NaN

In [10]:
Carbon_intensity = ghg_emissions[["Material", "GWP avg"]]
Carbon_intensity = Carbon_intensity.head(7)
Carbon_intensity

    Material    GWP avg
0   Concrete   0.206481
1      Brick   0.189735
2       Wood   0.055150
3      Steel   1.105450
4     Glass    2.650200
5  Aluminium  10.000500
6     Copper   7.318000